apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: helloworld-app-placement
  namespace: helloworld
  labels:
    app: helloworld-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      usage: development
