apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: s390x-sleep
  namespace: s390x-sleep
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - s390x-sleep-app
