apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: s390x-sleep-app-placement
  namespace: s390x-sleep
  labels:
    app: s390x-sleep-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      usage: development
