apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: fep-helm-operator
  namespace: fep-helm-operator
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fep-helm-operator-app
