---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: my-secrets
  namespace: my-secrets
  labels:
    app: my-secret
spec:
  channel: my-secrets-ch/my-secrets
  packageFilter:
    annotations:
      secretname: my-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: my-secrets-placement



