apiVersion: apps/v1
kind: Deployment
metadata:
  name: s390x-sleep
spec:
  selector:
    matchLabels:
      name: s390x-sleep
  replicas: 1
  template:
    metadata:
      labels:
        name: s390x-sleep
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: s390x-sleep
        image: quay.io/xiangjingli/s390x-sleep:latest
        imagePullPolicy: Always
        name: s390x-sleep
      serviceAccount: s390x-sleep
      serviceAccountName: s390x-sleep
